environments:
  bare_metal_pypi_package:
    environments:
      GIT_USER: "{{SECRET:[github][username]}}"
      PYPI_USERNAME: '{{SECRET:[jhub_authenticators][username]}}'
      PYPI_PASSWORD: '{{SECRET:[jhub_authenticators][password]}}'
    pipelines:
      - jhub-authenticators
pipelines:
  jhub-authenticators:
    group: bare_metal_pypi_package
    locking: off
    timer:
      # Run on the 1st at 00:00 of every month
      spec: "0 0 0 1 * ? *"
      only_on_changes: no
    materials:
      jhub-authenticators_git:  # this is the name of material
        # says about type of material and url at once
        git: https://github.com/ucphhpc/jhub-authenticators.git
        branch: master
        destination: jhub-authenticators
      publish_python_git:
        git: https://github.com/rasmunk/publish-python-scripts.git
        branch: main
        username: ${GIT_USER}
        password: "{{SECRET:[github][access_token]}}"
        destination: publish-python-scripts
    parameters:
      ARGS: ''
      SRC_DIRECTORY: jhub-authenticators
      TEST_DIRECTORY: jhub-authenticators
      PUSH_DIRECTORY: publish-python-scripts
      PYPI_USERNAME: ${PYPI_USERNAME}
      PYPI_PASSWORD: ${PYPI_PASSWORD}
    template: bare_metal_pypi_package
