environments:
  pypi_package:
    environments:
      GIT_USER: "{{SECRET:[github][username]}}"
    pipelines:
      - jhub-authenticators
pipelines:
  jhub-authenticators:
    group: pypi_package
    locking: off
    materials:
      jhub-authenticators_git:  # this is the name of material
        # says about type of material and url at once
        git: https://github.com/ucphhpc/jhub-authenticators.git
        branch: master
        destination: jhub-authenticators
      publish_python_git:
        git: https://github.com/rasmunk/publish-python-scripts.git
        branch: main
        username: ${GIT_USER}
        password: "{{SECRET:[github][access_token]}}"
        destination: publish-python-scripts
    parameters:
      ARGS: ''
      SRC_DIRECTORY: jhub-authenticators
      TEST_DIRECTORY: jhub-authenticators
      PUSH_DIRECTORY: publish-python-scripts
    template: pypi_package
